config/routes.rb
Rails.application.routes.draw do
	root 'students#index'
	resources :students do
		member do
			get :delete
		end
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
	validates_presence_of :first_name, :last_name, :email, :password
	validates_length_of :first_name, :last_name, :maximum =>10
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mark.rb
class Mark < ApplicationRecord
	validates_presence_of :marks, :subject_id
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :subjects
	validates_presence_of :student_name, :rollno
	validates_length_of :student_name, :maximum =>10
end

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :student
	validates_presence_of :subject_name, :student_id
	validates_length_of :subject_name, :maximum =>10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to(students_path)
    else
      render('new')
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      redirect_to(students_path(@student))
    else
      render('edit')
    end

  end

  def delete
    @student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to(students_path)
  end

  private 
    def student_params
      params.required(:student).permit(:student_name,:rollno)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddStudent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/delete.html.erb
<%= link_to("Back To List",students_path,:class => 'back-link')%>
<div class="subject delete">
	<h1>Delete Subject</h1>
	<%= form_for(@student,:url => student_path(@student),:method => 'delete')do |f|%>
	<p>Are you sure u want to delete this student</p>
	<p class="reference-name"><%= @student.student_name%></p>

	<div class="form-buttons">
		<%=f.submit("Delete Student")%>
	</div>
	<%end%>
</div> 

app/views/students/edit.html.erb
<%= link_to("Back To List", students_path,:class => 'back-link')%>
<div class="student new">
	<h1>Update Student</h1>
	<%= form_for(@student,:url => student_path(@student),:method => 'patch')do |f|%>
	<table summary="Student for fields">
		<tr>
			<th>Name</th>
			<td><%= f.text_field(:student_name)%></td>
		</tr>
		<tr>
			<th>Rollno</th>
			<td><%= f.text_field(:rollno)%></td>
		</tr>
	</table>
	<div class="form-buttons">
		<%= f.submit("Update Student")%>
	</div>
	<%end%>
</div>

app/views/students/index.html.erb
<div class="Student index">
	<h1>Students</h1>
	<%= link_to("Add new Student", 'students/new', :class => 'action new' )%>

	<table class="listing" summary="Student list">
		<tr class="header">
			<th>Student</th>
			<th>rollno</th>
			<th>Subject</th>
			<th>Action</th>
		</tr>
		<%@students.each do |student|%>
		<tr>
			<td><%= student.student_name %></td>
			<td><%= student.rollno %></td>
			<td class="center"><%=student.subjects.size%></td>
			<td class="action">
				<%= link_to("Show", student_path(student.id),:class =>'action show')%>
				<%= link_to("Edit", edit_student_path(student.id),:class =>'action edit')%>
				<%= link_to("Delete",delete_student_path(student.id),:class =>'action delete')%>
			</td>
		</tr>
		<%end%>
	</table>
</div>

app/views/students/new.html.erb
<%= link_to("Back To List", students_path,:class => 'back-link')%>
<div class="student new">
	<h1>Create Student</h1>
	<%= form_for(@student,:url => students_path,:method => 'post')do |f|%>
	<table summary="Student for fields">
		<tr>
			<th>Name</th>
			<td><%= f.text_field(:student_name)%></td>
		</tr>
		<tr>
			<th>Rollno</th>
			<td><%= f.text_field(:rollno)%></td>
		</tr>
	</table>
	<div class="form-buttons">
		<%= f.submit("Create Student")%>
	</div>
	<%end%>
</div>

app/views/students/show.html.erb
<%= link_to("Back To List",students_path,:class => 'back-link')%>
<div class="student show">
	<h1>Show Student</h1>
	<table summary="Student details view">
		<tr>
			<th>Name</th>
			<td><%= @student.student_name %></td>
		</tr>
		<tr>
			<th>Rollno</th>
			<td><%= @student.rollno %></td>
		</tr>
		<tr>
			<th>Created</th>
			<td><%= @student.created_at %></td>
		</tr>
			<th>Updated</th>
			<td><%= @student.updated_at %></td>
		</tr>
	</table>
</div>